### ISSUE TITLE
Missing sdm660-common-vendor.mk

### ISSUE THREAD

**Issue by thatreguy** [LineageOS/android_device_motorola_payton#10]
I'm trying to build lineage OS for payton and following the instructions on this page: https://wiki.lineageos.org/devices/payton/build
While executing the command ```breakfast payton``` I get the following error:

```device/motorola/sdm660-common/common.mk:396: error: _nic.PRODUCTS[[device/motorola/payton/lineage_payton.mk]]:"vendor/motorola/sdm660-common/sdm660-common-vendor.mk" does not exist.08:16:58 dumpvars failed with: exit status 1```

Digging deeper I found this to be the culprit line:
device/motorola/sdm660-common/common.mk:25
```$(call inherit-product, vendor/motorola/sdm660-common/sdm660-common-vendor.mk)```

I've searched everywhere for this file but could not find it. How do I resolve this error? Please help.

**Comment by daedroza** [comment]
https://github.com/TheMuppets/proprietary_vendor_motorola
