### ISSUE TITLE
No VoLTE on Verizon

### ISSUE THREAD

**Issue by aerusso** [LineageOS/android_device_motorola_payton#3]
Running Lineage 16.0 on a Moto X4, on Verizon. I've updated modem and fsg partitions from another, (new) donor moto x4 (baseband is at `M660_7042.27.01.95R`). Like this [user](https://github.com/LineageOS/android_device_motorola_payton/issues/2#issuecomment-480048525), I am not able to use voice/sms while connected to LTE, though on the donor phone, using the same SIM card, everything works fine. Using `*#*#4636#*#*` shows that I am not VoLTE provisioned, I do not have an "advanced calling" option under Network Settings, and the phone does not automatically connect to LTE (though I can force it to). Data works perfectly fine when forced to connect to LTE.

Another [comment](https://github.com/LineageOS/android_device_motorola_payton/issues/2#issuecomment-480176570) suggests that this Verizon issue is a separate issue from the Sprint issue of that thread.

I am therefore opening the Verizon issue here. It seems to be relatively [well](https://forum.xda-developers.com/showpost.php?p=78958428&postcount=842) [known](https://forum.xda-developers.com/showpost.php?p=78958428&postcount=844), and there may be some [leads](https://forum.xda-developers.com/showpost.php?p=78958428&postcount=1169).

I'm able (and willing) to test changes.

**Comment by jonorthwash** [comment]
@aerusso, were you able to resolve the issue?

By the way, I'm not even able to force LTE.  But I probably need to update the `modem` and `fsg` partitions as you did.  Would you mind sharing these?

**Comment by aerusso** [comment]
@jonorthwash I opened a bug on the [real bugtracker on gitlab](https://gitlab.com/LineageOS/issues/android/issues/677). Lets move our discussion there (and could you "thumbs-up" it so that people recognize it's important?).

Have you tried wiping modemst1 and modemst2? That's the first step I'd try.
