### ISSUE TITLE
No VoLTE on Verizon

### ISSUE THREAD

**Issue by joe-libertyman** [LineageOS/android_device_motorola_payton#7]
I am opening a new issue on LineageOS 16. I did double check an Android Stock ###exact model### and it works fine as Enhanced 4G LTE option. Examined default.prop (don't know if this is the right file) and LineageOS 16 is identical to Andriod stock. Does anyone have any pointers on how to fix this issue? Users cannot use data while on an active call with this feature not enabled. * # * #4636# * # * yields that the option is disabled. Not sure how to get this option enabled. Thanks.

This is on a  MOTO X4 64GB version. Everything works good but VoLTE. No Wifi calling either. Any help is greatly appreciated and thank you ahead of time.

**Comment by knuxyl** [comment]
I do not have Wifi calling, but VoLTE works perfectly fine. I have the Retail USA version, which one do you have because that is probably why it's not working, or Verizon has the feature VoLTE turned off for your number (used to be an option on the website).Might wanna call and check

**Comment by joe-libertyman** [comment]
I bought an unlocked version. It is not branded by any carrier. If I flash stock Android to it, it works fine. I spent over an hour on the phone with Tier II support at Verizon and they told me everything looked fine and they were aware that I had unlocked LineageOS phone. Last I heard they were taking it to their engineering department. I am not the only one with this issue. If you head over to GitLab you can see others have the same issue. Thank you for the information though, it does help some.

**Comment by daedroza** [comment]
@

> I am opening a new issue on LineageOS 16. I did double check an Android Stock ###exact model### and it works fine as Enhanced 4G LTE option. Examined default.prop (don't know if this is the right file) and LineageOS 16 is identical to Andriod stock. Does anyone have any pointers on how to fix this issue? Users cannot use data while on an active call with this feature not enabled. * # * #4636# * # * yields that the option is disabled. Not sure how to get this option enabled. Thanks.
> 
> This is on a MOTO X4 64GB version. Everything works good but VoLTE. No Wifi calling either. Any help is greatly appreciated and thank you ahead of time.

I have build that fixes it. Can you please contact me on Telegram, @daedroza 
Thanks!

**Comment by scramblr** [comment]
What is the difference with your version @daedroza ?

**Comment by daedroza** [comment]
@scramblr : It is supposed to work, since there is no custom VoLTE icon, you can simply check during call if LTE icon on signal bar changes to 3G during call, if it changes, then VoLTE is not present. If it's stable on LTE during calls too, your ims is working fine.

**Comment by joe-libertyman** [comment]
This was solved last year.... Forgot to close
